### ISSUE TITLE
With multiple keys bound to a button, the button is not triggered when hitting one key while some other key is down.

### ISSUE THREAD

**Issue by Rhacoal** [BroGamer4256/macros#1]
For example, with this configuration:
```
[[override]]
buttons = ["TRIANGLE"]
keys = ["CONTROLLER_L1", "CONTROLLER_L2"]
```

When either L1 or L2 is held, hitting the other does not trigger the button, and no SE is played. Tested using an XBOX controller with a Windows PC.

Mod version: 0.3
Game version: 1.04 (with DIVA Mod Loader v0.0.12)

**Comment by BroGamer4256** [comment]
Yes this is known and intentional behavior, if you want multiple keys to work like this you need two overrides.
